
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tdog_api_development

test:
  <<: *default
  database: tdog_api_test

production:
  primary: &primary_production
    <<: *default
    database: tdog_api_production
    username: tdog_api
    password: <%= ENV["TDOG_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tdog_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tdog_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tdog_api_production_cable
    migrations_paths: db/cable_migrate
